name: Build and deploy beskarweb
env:
  AZURE_WEBAPP_DEV: beskarweb-dev    
  AZURE_WEBAPP_cert: beskarweb-cert
  AZURE_WEBAPP_prod: beskarweb-prod
  AZURE_WEBAPP_PACKAGE_PATH: "./publish" 
  DOTNET_VERSION: '7.x'
  PROJECT_TEST_PATH: "WebApi.Tests/WebApi.Tests.csproj"
  PROJECT_BUILD_SLN : "./DemoWebApi.sln"
  PROJECT_APP_PUBLISH: "WebApi/WebApi.csproj"

on:  
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: build-on-deploy
  cancel-in-progress: true

jobs:
  #build-sonarcube:
    #uses: ./.github/workflows/sonarcloud.yml
    #secrets:
      #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-deploy-dev:
    runs-on: ${{matrix.os}}
    environment: Dev
    strategy:
      matrix:
        os: [ubuntu-latest]

    #needs: build-sonarcube
    
    steps:
      - uses: actions/checkout@v3   

      - name: Instalando .net core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Dependencies in cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Restaurar paquetes
        run: dotnet restore ./DemoWebApi.sln

      - name: Build
        run: dotnet build ./DemoWebApi.sln --configuration Release

      - name: Run tests 
        run: dotnet test ${{env.PROJECT_TEST_PATH}} --no-restore --verbosity normal      
  
      - name: publish
        run: dotnet publish ${{env.PROJECT_APP_PUBLISH}} -c Release --no-build -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
  
      - name: Deploy Dev
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          package: /home/runner/work/BeskarDemo1/BeskarDemo1/publish
          
  deploy-Cert:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-deploy-dev
    environment:
      name: 'Cert'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          package: /home/runner/work/BeskarDemo1/BeskarDemo1/publish
    
